services:
  app:
    build:
      context: .
    ports:
      - 80:5000
    volumes:
      - .:/app

  db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: operation_db
          MYSQL_USER: user
          MYSQL_PASSWORD: user

      volumes:
          - ./db:/docker-entrypoint-initdb.d

  adminer:
      image: adminer
      restart: always
      ports:
          - 8080:8080